resource_types:
- name: file-downloader
  type: docker-image
  source:
    repository: pivotalservices/file-downloader-resource

- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: pivnet-files
  type: file-downloader
  source:
    config_provider: git
    version_root: {{version_root}}
    uri: {{git_repo}}
    private_key: ((git_private_key.private_key))
    branch: master
    file_provider: pivnet
    pivnet_token: ((pivnet_token))

- name: platform-automation-config
  type: git
  source:
    uri: {{git_repo}}
    private_key: ((git_private_key.private_key))

- name: state
  type: gcs-resource
  source:
    bucket: ((state_bucket))
    json_key: ((state_bucket_key))
    versioned_file: state.yml

- name: pipeline-utilities
  type: git
  source:
    uri: https://github.com/pivotalservices/pipeline-utilities.git

jobs:
- name: upgrade-opsman
  serial: true
  plan:
  - aggregate:
    - get: platform-automation-image
      resource: pivnet-files
      params:
        product: platform-automation-image
        unpack: true
    - get: platform-automation-tasks
      resource: pivnet-files
      params:
        product: platform-automation-tasks
        unpack: true
    - get: pipeline-utilities
    - get: platform-automation-config
    - get: state
    - get: image
      resource: pivnet-files
      params:
        product: opsman
  - aggregate:
    - task: create-env-file
      file: pipeline-utilities/tasks/create-env-file.yml
      params:
        OPSMAN_TARGET: {{opsman_target}}
        OPSMAN_CONNECT_TIMEOUT: 1600
        OPSMAN_REQUEST_TIMEOUT: 600
        OPSMAN_SKIP_SSL_VALIDATION: true
        OPSMAN_USERNAME: {{opsman_username}}
        OPSMAN_PASSWORD: ((opsman_password))
        OPSMAN_DECRYPTION_PASSPHRASE: ((opsman_decryption_passphrase))

    - task: create-auth-file
      file: pipeline-utilities/tasks/create-auth-file.yml
      params:
        OPSMAN_DECRYPTION_PASSPHRASE: ((opsman_decryption_passphrase))
      output_mapping:
        config: auth
  
    - task: create-opsman-secrets
      file: pipeline-utilities/tasks/create-product-secrets.yml
      params:
        PRODUCT_opsman_service_account_json: ((opsman_service_account_json))

  - task: merge-concourse-inputs
    file: pipeline-utilities/tasks/merge-concourse-inputs.yml  
    input_mapping:
      input-folder1: auth
      input-folder2: platform-automation-config
    output_mapping:
      output-folder: config 

  - task: export-opsman-installation
    image: platform-automation-image
    file: platform-automation-tasks/tasks/export-installation.yml

  - task: upgrade-opsman-installation
    image: platform-automation-image
    file: platform-automation-tasks/tasks/upgrade-opsman.yml
    input_mapping:
      vars: platform-automation-config
    params:
      VARS_FILES: {{opsman_vars_files}}
      OPSMAN_CONFIG_FILE: templates/opsman.yml
    ensure:
      put: state
      params: { file: generated-state/state.yml }

  - task: apply-director-changes
    image: platform-automation-image
    file: platform-automation-tasks/tasks/apply-director-changes.yml
