{
 "title": "Static App Error Budget",
 "tags": [
  "gcp",
  "app"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "SLO",
    "label": "SLO (%)",
    "query": "99.999, 99.99, 99.9, 99, 99.5, 95"
   }
  ]
 },
 "panels": [
  { "title": "Static App GSLB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Error Budget (Rolling 30d)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "30*24*60*(1-$SLO/100)- avg(count_over_time(probe_success{instance=\"http://static-app.apps.gcp.mfisch.io\"}[30d]) - sum_over_time(probe_success{instance=\"http://static-app.apps.gcp.mfisch.io\"}[30d]))"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"http://static-app.apps.gcp.mfisch.io\"})",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(probe_http_status_code{instance=\"http://static-app.apps.gcp.mfisch.io\"})",
     "legendFormat": "Status Code"
    }
   ]
  },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(probe_success{instance=\"http://static-app.apps.gcp.mfisch.io\"})"
    }
   ]
  },
  { "title": "Static App PCF Central", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(probe_success{instance=\"http://static-app.apps.central.gcp.mfisch.io\"})"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"http://static-app.apps.central.gcp.mfisch.io\"})",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(probe_http_status_code{instance=\"http://static-app.apps.central.gcp.mfisch.io\"})",
     "legendFormat": "Status Code"
    }
   ]
  },
  { "title": "Static App PCF West", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "min(probe_success{instance=\"http://static-app.apps.west.gcp.mfisch.io\"})"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(probe_duration_seconds{instance=\"http://static-app.apps.west.gcp.mfisch.io\"})",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 14, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(probe_http_status_code{instance=\"http://static-app.apps.west.gcp.mfisch.io\"})",
     "legendFormat": "Status Code"
    }
   ]
  }
 ]
}