org: staticapp
space: demo
space-developer:
  ldap_users: []
  users:
  - joe
  - matt
  saml_users: []
  ldap_groups: []
space-manager:
  ldap_users:
  users: []
  saml_users: []
  ldap_groups: []
space-auditor:
  ldap_users: []
  users: []
  saml_users: []
  ldap_groups: []
allow-ssh: true
enable-space-quota: false
memory-limit: 0
instance-memory-limit: 0
total-routes: 0
total-services: 0
paid-service-plans-allowed: false
enable-security-group: false
enable-remove-users: true
total_private_domains: 0
total_reserved_route_ports: 0
total_service_keys: 0
app_instance_limit: 0
app_task_limit: 0
named-security-groups: []