---
platform: linux

image_resource:
  type: docker-image
  source: {repository: pivotalservices/cf-mgmt, tag: "latest"}

inputs:
  - name: config-repo

run:
  path: config-repo/cf-mgmt/ci/tasks/cf-mgmt.sh
